### ISSUE TITLE
Frontend mal anders - Amazon Alexa statt Browser

### ISSUE THREAD

**Issue by fisherman90** [frontend-rhein-neckar/talk-proposals#10]
## Titel des Talks
Frontend mal anders - Amazon Alexa statt Browser

## Länge des Talks
ca. 30min.

## Zusammenfassung (140 Zeichen)
Amazon Alexa - ebenso ein Frontend wie der Browser. Nur anders 😄 Wie schafft man einen einfachen Alexa skill? Welche Tools braucht man?

## Detaillierte Zusammenfassung
Sprachassistenten wie Amazon Alexa, Google now und Siri sind non-visuelle Frontends, welche immer mehr Bedeutung in unsrerem alltäglichem Leben spielen. In dieser Session lernt ihr am Beispiel von Amazon Alexa, wie einfach ihr euer bestehendes Web-Backend (als Beispiel Drupal, aber das Prinzip trifft auf alle zu) an diese Services hängen könnt und welche Tools ihr zur Entwicklung benötigt.

**Comment by bitbruder** [comment]
Schön wars!
