### ISSUE TITLE
Gatsby - Mehr als ein Static Site Generator

### ISSUE THREAD

**Issue by LekoArts** [frontend-rhein-neckar/talk-proposals#11]
## Titel des Talks
Gatsby - Mehr als ein Static Site Generator

## Länge des Talks
ca. 45 Minuten

## Zusammenfassung (140 Zeichen)

Gatsby ist nicht nur für Blogs zu gebrauchen, sondern macht auch eCommerce Seiten rasend schnell. Einführung in Gatsby und das Ökosystem.

## Detaillierte Zusammenfassung

Versuch einer Definition was Gatsby eigentlich ist, und warum es Websiten von Haus aus so schnell macht. Auch wird der Datenfluss inkl. GraphQL Ebene erklärt und dahingehend auf z.B. `gatsby-image` weitergeleitet. Auch das Ökosystem von Gatsby kann sich sehen lassen mit seinen vielen Fans, Templates, Plugins und Events. Am Ende soll es darum gehen, dass Gatsby geeignet ist, um React zu lernen, aber auch andere Technologien zu vertiefen (z.B. GraphQL). Eine hybride (static + dynamic) App als Demo rundet den Vortrag ab.

Danach folgt eine Live-Demo in der ich den [hello-world](https://github.com/gatsbyjs/gatsby-starter-hello-world) Starter installiere und erweitere.

## Hinweise

- Die Folien sind auf Englisch, der Vortrag wird natürlich auf Deutsch gehalten (zumindest habe ich den Eindruck, dass das so gewünscht ist)
- Bei Twitter, Meetup und Co. bitte immer **nur** "Lennart" (Vorname) für die Erwähnungen nehmen, also z.B. `"Am X. März zeigt uns Lennart (@lekoarts_de) warum Gatsby mehr als ein Static Site Generator ist"`
- Ich bringe ein paar [Gatsby Sticker](https://store.gatsbyjs.org/product/gatsby-sticker-6-pack) mit 👍

**Comment by bitbruder** [comment]
Hey Lennart 👋 

Vielen Dank für den spannenden Vorschlag. Wir geben Dir bescheid, sobald der Termin für unser nächstes Meetup steht. @DanielRuf coming up

**Comment by bitbruder** [comment]
Danke für Deine Zeit Lennart, hat Spaß gemacht! 

> Die Slides zum Talk könnt ihr hier finden: https://gatsby.lekoarts.de/
> 
> Zu der Live-Programmier Session gibt es ein Repo von Lennart, das in einzelnen Commits den Verlauf zeigt. So könnt ihr das nochmal in Ruhe nachvollziehen: https://github.com/LekoArts/gatsby-from-scratch
> 
> Wenn ihr noch Fragen habt oder zeigen wollt, was ihr nun mit Gatsby gebaut habt, könnt ihr Lennart gerne eine Email schreiben https://www.lekoarts.de/contact
