### ISSUE TITLE
Web Components und was sie für dich tun können

### ISSUE THREAD

**Issue by DominicBoettger** [frontend-rhein-neckar/talk-proposals#12]
## Länge des Talks
ca 60 Minuten

## Zusammenfassung (140 Zeichen)
Wie man Webcomponents effizient einsetzt und man durch deren Einsatz Entwicklungsprojekte vereinfacht und beschleunigt.

## Detaillierte Zusammenfassung

Aktuelle Entwicklungsprojekte entstehen üblicherweise mit der Unterstützung von Frameworks und Javascript-Bibliotheken. Jedes Framework hat seine eigene Community und jede Version bringt neue Funktionen und mehr Performance. Oft müssen für ein Update oder Upgrade die Applikation und Komponenten angepasst werden. Diese Aufgaben sind teuer, fehleranfällig und dadurch nicht nachhaltig.

Alexander und Dominic gewähren einen Einblick in ihre Arbeit, bei der es hauptsächlich darum geht, die Performance von Entwicklungsteams zu verbessern und das Design von Applikationen und die Stabilität des Entwicklungs- und Deployment-Prozesses durch Tests zu optimieren. Am Beispiel ihres Kunden Sixt Rides demonstrieren sie, wie man Oberflächenbibliotheken frameworkunabhängig mit Web Components entwickelt und automatisiert testet, um jederzeit Deployments realisieren zu können.

**Comment by bitbruder** [comment]
Wir freuen uns auf Deinen Talk am 19.06.19!

**Comment by bitbruder** [comment]
Super wars! Danke euch. Vielleicht möchtet ihr ja noch die Slides in die Gruppe posten.
