### ISSUE TITLE
Gulp - Ein praktischer Einstieg

### ISSUE THREAD

**Issue by cod3cow** [frontend-rhein-neckar/talk-proposals#3]
## Titel des Talks
Gulp - Ein praktischer Einstieg

## Länge des Talks
30 Minuten

## Zusammenfassung 
In einem kurzen Beispiel wird live gezeigt, wie Du von Grund auf ein Frontend-Projekt mit Gulp startest. Gulp soll automatisch Deine SASS-Styles in CSS kompilieren, Dein JavaScript komprimieren und den Browser danach aktualiseren.

**Comment by bitbruder** [comment]
Hey @Bloggerschmidt! Wie bereits mit @DanielRuf besprochen, würden wir uns freuen wenn du den Talk direkt zu [0.1] am 29.05.18 halten könntest. Falls du Fragen oder weitere Hilfe brauchst, kannst du uns gerne direkt kontaktieren. 📫 👍
